<?php
session_start();
require_once 'config.php';
require_once 'includes/functions.php';
require_once 'includes/module3_functions.php';

// Security Check
if (!isset($_SESSION['userID']) || $_SESSION['role'] !== 'lecturer') {
    header('Location: login.php');
    exit;
}

$lecturerID = $_SESSION['userID'];
$filterCourse = isset($_GET['course_id']) ? $_GET['course_id'] : 'all';
// Detect if we are in "Print Mode"
$isPrintView = (isset($_GET['print']) && $_GET['print'] == '1');

// --- 1. DATA FETCHING ---
$courseSql = "SELECT courseID, courseName FROM course WHERE userID = ?";
$stmt = $conn->prepare($courseSql);
$stmt->bind_param("i", $lecturerID);
$stmt->execute();
$allCourses = $stmt->get_result();

$sql = "SELECT u.userID, u.full_name, c.courseName, c.courseID 
        FROM enrollment e 
        JOIN course c ON e.courseID = c.courseID 
        JOIN user u ON e.userID = u.userID 
        WHERE c.userID = ?";

if ($filterCourse !== 'all') {
    $sql .= " AND c.courseID = ?";
}

$stmt = $conn->prepare($sql);
if ($filterCourse !== 'all') {
    $stmt->bind_param("ii", $lecturerID, $filterCourse);
} else {
    $stmt->bind_param("i", $lecturerID);
}
$stmt->execute();
$result = $stmt->get_result();

// --- 2. AGGREGATES ---
$totalScore = 0;
$totalAtt = 0;
$studentCount = 0;
$atRiskCount = 0;
$assessmentsCount = 0;
$studentList = [];
$gradeDist = ['A'=>0, 'B'=>0, 'C'=>0, 'D'=>0, 'F'=>0];
$courseavgs = []; 

while ($row = $result->fetch_assoc()) {
    $avg = calculate_course_average($conn, $row['userID'], $row['courseID']);
    $att = calculate_attendance_rate($conn, $row['userID'], $row['courseID']);
    $status = get_student_status($avg, $att);

    $cntSql = "SELECT COUNT(*) as cnt FROM submission s 
               JOIN assessment a ON s.assessmentID = a.assessmentID 
               WHERE s.userID = ? AND a.courseID = ?";
    $cStmt = $conn->prepare($cntSql);
    $cStmt->bind_param("ii", $row['userID'], $row['courseID']);
    $cStmt->execute();
    $cnt = $cStmt->get_result()->fetch_assoc()['cnt'];
    $assessmentsCount += $cnt;

    $totalScore += $avg;
    $totalAtt += $att;
    $studentCount++;
    if ($status['label'] === 'At Risk') $atRiskCount++;

    if ($avg >= 80) $gradeDist['A']++;
    elseif ($avg >= 70) $gradeDist['B']++;
    elseif ($avg >= 60) $gradeDist['C']++;
    elseif ($avg >= 50) $gradeDist['D']++;
    else $gradeDist['F']++;

    if (!isset($courseavgs[$row['courseName']])) {
        $courseavgs[$row['courseName']] = ['total' => 0, 'count' => 0];
    }
    $courseavgs[$row['courseName']]['total'] += $avg;
    $courseavgs[$row['courseName']]['count']++;

    $studentList[] = [
        'id' => 'CB' . str_pad($row['userID'], 5, '0', STR_PAD_LEFT),
        'raw_id' => $row['userID'],
        'course_id' => $row['courseID'], // ADDED THIS: Store the specific course ID for this row
        'name' => $row['full_name'],
        'course' => $row['courseName'],
        'avg' => $avg,
        'att' => $att,
        'status' => $status
    ];
}

$globalAvg = $studentCount > 0 ? round($totalScore / $studentCount, 1) : 0;
$globalAtt = $studentCount > 0 ? round($totalAtt / $studentCount, 1) : 0;

$barLabels = array_keys($courseavgs);
$barData = [];
foreach ($courseavgs as $c) {
    $barData[] = round($c['total'] / $c['count'], 1);
}

// --- 3. TREND DATA ---
$trendSql = "SELECT 
                DATE_FORMAT(s.submitDate, '%Y-%u') as week_key,
                AVG(s.grade) as weekly_avg 
             FROM submission s
             JOIN assessment a ON s.assessmentID = a.assessmentID
             JOIN course c ON a.courseID = c.courseID
             WHERE c.userID = ? 
             " . ($filterCourse !== 'all' ? "AND c.courseID = ?" : "") . "
             GROUP BY week_key
             ORDER BY week_key ASC
             LIMIT 10";

$tStmt = $conn->prepare($trendSql);
if ($filterCourse !== 'all') {
    $tStmt->bind_param("ii", $lecturerID, $filterCourse);
} else {
    $tStmt->bind_param("i", $lecturerID);
}
$tStmt->execute();
$trendResult = $tStmt->get_result();

$trendLabels = [];
$trendData = [];
$weekCounter = 1;

while ($row = $trendResult->fetch_assoc()) {
    $trendLabels[] = "Week " . $weekCounter++; 
    $trendData[] = round($row['weekly_avg'], 1);
}
if (empty($trendData)) { $trendLabels = ['No Data']; $trendData = [0]; }

// --- 4. EXCEL DOWNLOAD ---
if (isset($_GET['download']) && $_GET['download'] === 'excel') {
    $filename = "progress_report_" . date('Ymd_His') . ".csv";
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    $f = fopen('php://output', 'w');
    fputs($f, "\xEF\xBB\xBF");
    fputcsv($f, ['Academic Progress Report']);
    fputcsv($f, ['Generated By', $_SESSION['full_name']]);
    fputcsv($f, ['Date', date("d F Y")]);
    fputcsv($f, []); 
    fputcsv($f, ['SUMMARY STATISTICS']);
    fputcsv($f, ['Average Score', $globalAvg . '%']);
    fputcsv($f, ['Attendance Rate', $globalAtt . '%']);
    fputcsv($f, ['Assessments Completed', $assessmentsCount]);
    fputcsv($f, ['Students At Risk', $atRiskCount]);
    fputcsv($f, []); 
    fputcsv($f, ['Student ID', 'Name', 'Course', 'Average (%)', 'Attendance (%)', 'Status']);
    foreach ($studentList as $s) {
        fputcsv($f, [$s['id'], $s['name'], $s['course'], $s['avg'], $s['att'], $s['status']['label']]);
    }
    fclose($f);
    exit;
}

$reportDate = date("d F Y");
$lecturerName = $_SESSION['full_name'] ?? 'Lecturer';
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title><?php echo $isPrintView ? 'Report - Print View' : 'Lecturer Dashboard - EduTrack'; ?></title>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <style>
    /* === COMMON STYLES === */
    .status-badge {
        padding: 5px 12px;
        border-radius: 15px;
        color: white;
        font-size: 11px;
        font-weight: bold;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }

    /* === SCREEN ONLY STYLES (Hide these when printing) === */
    <?php if ( !$isPrintView): ?>.main-content {
        background-color: #e0f7fa;
        padding: 20px;
        min-height: 100vh;
    }

    .dashboard-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .filter-select {
        padding: 8px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }

    .title-badge {
        background: #f06292;
        color: white;
        padding: 8px 20px;
        border-radius: 20px;
        font-weight: bold;
    }

    /* Layout Fixes (Sticky Sidebar) */
    .content-wrapper {
        display: flex;
        align-items: flex-start;
        min-height: 100vh;
        position: relative;
    }

    .sidebar {
        width: 250px;
        flex-shrink: 0;
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        height: 100vh;
        overflow-y: auto;
    }

    .main-content {
        flex-grow: 1;
        width: 100%;
        overflow-x: hidden;
    }

    .cards-container {
        background: #80deea;
        padding: 20px;
        border-radius: 15px;
        display: flex;
        gap: 20px;
        margin-bottom: 20px;
    }

    .card {
        flex: 1;
        padding: 20px;
        border-radius: 15px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        color: #333;
    }

    .card h3 {
        font-size: 14px;
        margin-bottom: 10px;
        font-weight: normal;
    }

    .card .big-num {
        font-size: 24px;
        font-weight: bold;
    }

    .card-purple {
        background: #e1bee7;
    }

    .card-green {
        background: #b9f6ca;
    }

    .card-blue {
        background: #90caf9;
    }

    .card-red {
        background: #ff5252;
        color: white;
    }

    .charts-container {
        background: #80deea;
        padding: 20px;
        border-radius: 15px;
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: 20px;
        margin-bottom: 20px;
    }

    .chart-box {
        background: white;
        border-radius: 10px;
        padding: 10px;
        height: 220px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .chart-title {
        font-size: 12px;
        font-weight: bold;
        color: #555;
        margin-top: 10px;
    }

    .bottom-section {
        background: #80deea;
        padding: 20px;
        border-radius: 15px;
        display: flex;
        gap: 20px;
    }

    .table-wrapper {
        flex: 3;
        background: #e0e0e0;
        border-radius: 10px;
        overflow: hidden;
    }

    .custom-table {
        width: 100%;
        border-collapse: collapse;
        background: white;
    }

    .custom-table th {
        background: #eceff1;
        padding: 10px;
    }

    .custom-table td {
        padding: 10px;
        border-bottom: 1px solid #eee;
        text-align: center;
    }

    .action-sidebar {
        flex: 1;
        display: flex;
        flex-direction: column;
        gap: 10px;
    }

    .btn-action {
        padding: 15px;
        border: none;
        border-radius: 8px;
        font-weight: bold;
        cursor: pointer;
        color: #333;
    }

    .btn-pdf {
        background: #69f0ae;
    }

    .btn-excel {
        background: #e0e0e0;
        margin-top: 5px;
    }

    <?php else: ?>

    /* === PRINT VIEW STYLES (Only active in the new tab) === */
    body {
        background: #fff;
        font-family: 'Arial', sans-serif;
        color: #000;
        padding: 20px;
    }

    .header,
    .sidebar,
    .action-sidebar,
    .dashboard-header {
        display: none !important;
    }

    .content-wrapper {
        display: block;
    }

    .main-content {
        background: #fff;
        padding: 0;
        width: 100%;
    }

    .report-header {
        text-align: center;
        border-bottom: 2px solid #000;
        padding-bottom: 20px;
        margin-bottom: 30px;
    }

    .report-header img {
        width: 80px;
        margin-bottom: 10px;
    }

    .report-header h1 {
        font-size: 24px;
        margin: 5px 0;
        text-transform: uppercase;
        color: #000;
    }

    .report-meta {
        font-size: 12px;
        color: #555;
    }

    .summary-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 30px;
    }

    .summary-table th {
        background: #f0f0f0;
        border: 1px solid #ddd;
        padding: 10px;
        font-size: 11px;
        text-transform: uppercase;
    }

    .summary-table td {
        border: 1px solid #ddd;
        padding: 15px;
        text-align: center;
        font-size: 18px;
        font-weight: bold;
    }

    .charts-row {
        display: flex;
        justify-content: space-between;
        gap: 20px;
        margin-bottom: 30px;
        height: 260px;
    }

    .chart-item {
        flex: 1;
        border: 1px solid #eee;
        padding: 10px;
        text-align: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .chart-label {
        margin-top: 15px;
        font-weight: bold;
        font-size: 12px;
        text-transform: uppercase;
        color: #000;
    }

    .student-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 11px;
    }

    .student-table th {
        background: #333 !important;
        color: white !important;
        padding: 8px;
        text-align: left;
        -webkit-print-color-adjust: exact;
    }

    .student-table td {
        border-bottom: 1px solid #ddd;
        padding: 8px;
        text-align: left;
        color: #000;
    }

    .status-badge {
        border: 1px solid #000;
        color: #000 !important;
        padding: 4px 8px;
    }

    <?php endif;
    ?>
    </style>
</head>

<body>

    <?php if (!$isPrintView): ?>
    <div class="header lecturer-theme">
        <div class="brand">
            <img src="assets/logoedutrack.png" alt="EduTrack Logo">
            <div class="title">
                <h1>EduTrack</h1><span>Smart Tracking for Smarter Learning</span>
            </div>
        </div>
        <img src="assets/profile.png" class="profile-icon">
    </div>
    <?php endif; ?>

    <div class="content-wrapper">
        <?php if (!$isPrintView): ?>
        <div class="sidebar lecturer-theme">
            <ul>
                <li><a href="lecturer_dashboard.php">Assessment</a></li>
                <li><a href="lecturer_progress.php" style="background: rgba(255,255,255,0.6);">Progress</a></li>
                <li><a href="lecturer_myfeedback.php">My Feedback</a></li>
                <li><a href="studevaluationlist.php">Evaluation</a></li>
                <li><a href="profile.php">My Profile</a></li>
            </ul>
            <button class="logout-btn" onclick="window.location.href='logout.php'">Log Out</button>
        </div>
        <?php endif; ?>

        <div class="main-content">

            <?php if ($isPrintView): ?>
            <div class="report-header">
                <img src="assets/logoedutrack.png" alt="Logo">
                <h1>Academic Performance Report</h1>
                <div class="report-meta">
                    Generated by: <?php echo htmlspecialchars($lecturerName); ?> | Date: <?php echo $reportDate; ?><br>
                    Scope:
                    <?php echo ($filterCourse == 'all') ? 'All Active Courses' : 'Course ID #' . $filterCourse; ?>
                </div>
            </div>

            <table class="summary-table">
                <thead>
                    <tr>
                        <th>Average Score</th>
                        <th>Attendance Rate</th>
                        <th>Assessments</th>
                        <th>At Risk</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?php echo $globalAvg; ?>%</td>
                        <td><?php echo $globalAtt; ?>%</td>
                        <td><?php echo $assessmentsCount; ?></td>
                        <td style="color: #d32f2f;"><?php echo $atRiskCount; ?></td>
                    </tr>
                </tbody>
            </table>

            <div class="charts-row">
                <div class="chart-item">
                    <canvas id="pdfChart1"></canvas>
                    <span class="chart-label">Grade Distribution</span>
                </div>
                <div class="chart-item">
                    <canvas id="pdfChart2"></canvas>
                    <span class="chart-label">Performance Trend</span>
                </div>
            </div>

            <h3 style="font-size: 14px; border-bottom: 2px solid #ddd; padding-bottom: 5px;">Detailed Student
                Performance</h3>
            <table class="student-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Student Name</th>
                        <th>Course</th>
                        <th>Average</th>
                        <th>Att. Rate</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($studentList as $s): ?>
                    <tr>
                        <td><?php echo $s['id']; ?></td>
                        <td><?php echo htmlspecialchars($s['name']); ?></td>
                        <td><?php echo htmlspecialchars($s['course']); ?></td>
                        <td><?php echo $s['avg']; ?>%</td>
                        <td><?php echo $s['att']; ?>%</td>
                        <td><span class="status-badge"
                                style="background-color: <?php echo $s['status']['color']; ?>;"><?php echo $s['status']['label']; ?></span>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <?php else: ?>

            <div class="dashboard-header">
                <form method="GET">
                    <span style="font-weight: bold; color: #555;">Filter:</span>
                    <select name="course_id" class="filter-select" onchange="this.form.submit()">
                        <option value="all">All Courses</option>
                        <?php while($c = $allCourses->fetch_assoc()): ?>
                        <option value="<?php echo $c['courseID']; ?>"
                            <?php echo ($filterCourse == $c['courseID']) ? 'selected' : ''; ?>>
                            <?php echo htmlspecialchars($c['courseName']); ?>
                        </option>
                        <?php endwhile; ?>
                    </select>
                </form>
                <div class="title-badge">Progress Dashboard</div>
            </div>

            <div class="cards-container">
                <div class="card card-purple">
                    <h3>Average Score</h3>
                    <div class="big-num"><?php echo $globalAvg; ?>%</div>
                </div>
                <div class="card card-green">
                    <h3>Attendance Rate</h3>
                    <div class="big-num"><?php echo $globalAtt; ?>%</div>
                </div>
                <div class="card card-blue">
                    <h3>Assessments</h3>
                    <div class="big-num"><?php echo $assessmentsCount; ?></div>
                </div>
                <div class="card card-red">
                    <h3>At Risk Students</h3>
                    <div class="big-num"><?php echo $atRiskCount; ?></div>
                </div>
            </div>

            <div class="charts-container">
                <div class="chart-box">
                    <canvas id="screenChart1"></canvas>
                    <div class="chart-title">Student performance trend over time</div>
                </div>
                <div class="chart-box">
                    <canvas id="screenChart2"></canvas>
                    <div class="chart-title">Course comparison (average mark)</div>
                </div>
                <div class="chart-box">
                    <canvas id="screenChart3"></canvas>
                    <div class="chart-title">Grade distribution (A-F)</div>
                </div>
            </div>

            <div class="bottom-section">
                <div class="table-wrapper">
                    <table class="custom-table">
                        <thead>
                            <tr>
                                <th>Student</th>
                                <th>Course</th>
                                <th>Avg</th>
                                <th>Att</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($studentList as $s): ?>
                            <tr>
                                <td>
                                    <a href="lecturer_view_student.php?student_id=<?php echo $s['raw_id']; ?>&course_id=<?php echo $s['course_id']; ?>"
                                        style="color: #00bcd4; font-weight: bold; text-decoration: none;">
                                        <?php echo htmlspecialchars($s['name']); ?>
                                    </a>
                                </td>
                                <td><?php echo htmlspecialchars($s['course']); ?></td>
                                <td><?php echo $s['avg']; ?>%</td>
                                <td><?php echo $s['att']; ?>%</td>
                                <td><span class="status-badge"
                                        style="background-color: <?php echo $s['status']['color']; ?>"><?php echo $s['status']['label']; ?></span>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="action-sidebar">
                    <button class="btn-action btn-pdf"
                        onclick="window.open('lecturer_progress.php?print=1&course_id=<?php echo $filterCourse; ?>', '_blank')">Download
                        PDF</button>
                    <button class="btn-action btn-excel"
                        onclick="window.location.href='?download=excel&course_id=<?php echo $filterCourse; ?>'">Download
                        Excel</button>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <script>
    const barLabels = <?php echo json_encode($barLabels); ?>;
    const barData = <?php echo json_encode($barData); ?>;
    const pieData = <?php echo json_encode(array_values($gradeDist)); ?>;
    const trendLabels = <?php echo json_encode($trendLabels); ?>;
    const trendData = <?php echo json_encode($trendData); ?>;

    <?php if (!$isPrintView): ?>
    // === SCREEN CHARTS ===
    if (document.getElementById('screenChart1')) {
        new Chart(document.getElementById('screenChart1'), {
            type: 'line',
            data: {
                labels: trendLabels,
                datasets: [{
                    label: 'Trend',
                    data: trendData,
                    borderColor: '#3f51b5',
                    fill: true,
                    backgroundColor: 'rgba(63, 81, 181, 0.1)',
                    tension: 0.3
                }]
            },
            options: {
                plugins: {
                    legend: {
                        display: false
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 100
                    }
                }
            }
        });
    }
    if (document.getElementById('screenChart2')) {
        new Chart(document.getElementById('screenChart2'), {
            type: 'bar',
            data: {
                labels: barLabels,
                datasets: [{
                    label: 'Avg',
                    data: barData,
                    backgroundColor: '#90caf9'
                }]
            },
            options: {
                plugins: {
                    legend: {
                        display: false
                    }
                }
            }
        });
    }
    if (document.getElementById('screenChart3')) {
        new Chart(document.getElementById('screenChart3'), {
            type: 'pie',
            data: {
                labels: ['A', 'B', 'C', 'D', 'F'],
                datasets: [{
                    data: pieData,
                    backgroundColor: ['#4caf50', '#cddc39', '#ffeb3b', '#ff9800', '#f44336']
                }]
            },
            options: {
                plugins: {
                    legend: {
                        position: 'right'
                    }
                }
            }
        });
    }
    <?php else: ?>
    // === PRINT CHARTS (Auto-Print) ===
    window.onload = function() {
        new Chart(document.getElementById('pdfChart1'), {
            type: 'pie',
            data: {
                labels: ['A', 'B', 'C', 'D', 'F'],
                datasets: [{
                    data: pieData,
                    backgroundColor: ['#4caf50', '#cddc39', '#ffeb3b', '#ff9800', '#f44336']
                }]
            },
            options: {
                plugins: {
                    legend: {
                        position: 'right',
                        labels: {
                            boxWidth: 10,
                            font: {
                                size: 9
                            }
                        }
                    }
                },
                animation: false
            }
        });

        new Chart(document.getElementById('pdfChart2'), {
            type: 'line',
            data: {
                labels: trendLabels,
                datasets: [{
                    label: 'Trend',
                    data: trendData,
                    borderColor: '#3f51b5',
                    fill: false,
                    tension: 0.3
                }]
            },
            options: {
                plugins: {
                    legend: {
                        display: false
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 100
                    }
                },
                animation: false
            }
        });

        setTimeout(() => {
            window.print();
        }, 800);
    };
    <?php endif; ?>
    </script>
</body>

</html>